<a href="https://colab.research.google.com/github/srishanth18varma/python_course_work/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print('1 Dimension', arr1, sep='\n', end='\n\n')

1 Dimension
[1 2 3 4 5]



In [4]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print('2 Dimension', arr2, sep = '\n', end = '\n\n')

2 Dimension
[[1 2 3]
 [4 5 6]]



In [5]:
arr3 = np.array([[[1, 2], [3, 4]], [[4, 5], [6, 7]]])
print('Multi Dimension', arr3, sep = '\n')

Multi Dimension
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [8]:
zeros = np.zeros((5, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
ones = np.ones((5, 5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
lin_space = np.linspace(1, 50, 2)
print(lin_space)

[ 1. 50.]


In [21]:
rand_int = np.random.randint(2, 22)
print(rand_int)

18


In [20]:
rand_float = np.random.rand(3, 3)
print(rand_float)

[[0.1968054  0.87752192 0.78100384]
 [0.55997534 0.12991771 0.04920393]
 [0.69308843 0.93198833 0.32048144]]


In [23]:
a = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
flattened = a.flatten()
print(flattened)

[1 2 3 4 1 2 3 4]


In [25]:
arr = np.array([10, 20, 30 ,40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [32]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix[0:2])
print()
print(matrix[0:3, 0])
print()
print(matrix[0:2, 0:2])

[[10 20 30]
 [40 50 60]]

[10 40 70]

[[10 20]
 [40 50]]


In [35]:
arr = np.array([4, 9, 16, 25, 36])
print(arr + 1)
print(arr * 2)
print(arr ** 2)
print(np.sqrt(arr))

[ 5 10 17 26 37]
[ 8 18 32 50 72]
[  16   81  256  625 1296]
[2. 3. 4. 5. 6.]


In [37]:
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

90
18.0
16.0


In [40]:
arr = np.array([1, 2, 3, 4, 5])
print(np.min(arr))
print(np.max(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]
